# -*- coding: utf-8 -*-
"""AVANCE DEL TRABAJO FINAL:

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uSVtTBhvOxUxiUw5yIRd2x2DFEUtXau

INTEGRANTES:
- Luis de la Cruz (20242006)
- Deyvid Blas (20256356)
"""

# CONECTAR GOOGLE COLAB CON LOS ARCHIVOS

from google.colab import files
import pandas as pd

# SUBIR LA BASE DE DATOS EN ARCHIVO EXCEL

print("📂 Subir Base de Datos\n")

uploaded = files.upload()

base_excel = list(uploaded.keys())[0]

# LEER LA BASE DE DATOS

df = pd.read_excel(base_excel)

# ESTABLECER LAS COLUMNAS

columnas_requeridas = [
    "nivel",
    "periodo",
    "cultura",
    "pregunta",
    "A",
    "B",
    "C",
    "D",
    "respuesta"
]

for columna in columnas_requeridas:
    if columna not in df.columns:
        print(f"❌ Falta la columna '{columna}' en el Excel.")
        raise SystemExit

# COLOCAR EL TÍTULO DEL JUEGO

print("-" * 80)
print("\n🦙🌄 Trivia sobre culturas prehispánicas")

# ORGANIZAR LA SELECCIÓN DE NIVELES

orden_niveles = ["Fácil", "Intermedio", "Difícil"]

niveles = [
    nivel for nivel in orden_niveles
    if nivel in df["nivel"].unique()
]

print("\n📚 Niveles disponibles:\n")

for i, nivel in enumerate(niveles, start=1):
    print(f"{i}. {nivel}")

while True:
    try:
        opcion = int(input("\nElige un nivel (número): "))

        if 1 <= opcion <= len(niveles):
            nivel_elegido = niveles[opcion - 1]
            break

        print("❌ Número fuera de rango.")

    except ValueError:
        print("❌ Debes ingresar un número.")

print(f"\n✅ Nivel seleccionado: {nivel_elegido}")

# FILTRAR LAS PREGUNTAS CORRESPONDIENTES AL NIVEL ELEGIDO

preguntas_nivel = df[df["nivel"] == nivel_elegido]

if len(preguntas_nivel) == 0:
    print("❌ No existen preguntas para ese nivel.")
    raise SystemExit

# SELECCIONAR 10 PREGUNTAS ALEATORIAMENTE

cantidad_preguntas = min(10, len(preguntas_nivel))

preguntas = preguntas_nivel.sample(
    n=cantidad_preguntas,
    random_state=None
)

puntaje = 0

# INICIO DEL JUEGO

for numero, (_, fila) in enumerate(
    preguntas.iterrows(),
    start=1
):

    print(f"📖 Pregunta {numero} de {cantidad_preguntas}")
    print(f"🕰️ Período: {fila['periodo']}")
    print(f"🗿 Cultura: {fila['cultura']}")

    print("\n🔷 PREGUNTA")
    print(f"{fila['pregunta']}")

    print(f"\nA) {fila['A']}")
    print(f"B) {fila['B']}")
    print(f"C) {fila['C']}")
    print(f"D) {fila['D']}")

    while True:

        respuesta = input(
            "\nTu respuesta (A/B/C/D): "
        ).strip().upper()

        if respuesta in ["A", "B", "C", "D"]:
            break

        print("‼️ Solo puedes responder A, B, C o D.")

    correcta = str(fila["respuesta"]).strip().upper()

    if respuesta == correcta:
        print("✅ ¡Correcto!")
        puntaje += 1
    else:
        print("❌ Incorrecto")
        print(f"Respuesta correcta: {correcta}")

# RESULTADOS CONSEGUIDOS

porcentaje = (puntaje / cantidad_preguntas) * 100

print("🏁 FIN DEL JUEGO")

print(f"\n➡️ Puntaje: {puntaje}/{cantidad_preguntas}")

if porcentaje == 100:
    print("🏆 ¡Perfecto!")
elif porcentaje >= 80:
    print("🌟 Excelente trabajo")
elif porcentaje >= 60:
    print("👏 Muy bien")
elif porcentaje >= 40:
    print("👀 Puedes mejorar")
else:
    print("📖 Sigue estudiando las culturas prehispánicas")

print("\n👌 ¡Gracias por jugar!")

"""#14
Reviso que el código está muy bien estructurado y cumple correctamente con la lógica principal del juego de trivia. Valoro que conectes Google Colab con un archivo Excel, valides que existan las columnas necesarias, permitas elegir un nivel, filtres las preguntas según esa selección y uses una muestra aleatoria de hasta 10 preguntas. También está bien implementada la validación de respuestas A/B/C/D y el cálculo final del puntaje con mensajes según el desempeño. Como mejora, agregaría una validación para el caso en que no haya niveles disponibles después de leer el Excel, y también revisaría que la columna “respuesta” solo contenga valores válidos entre A, B, C y D. En general, considero que es un trabajo completo, funcional y bien presentado.
"""

